### ISSUE TITLE
Failure to initialize!

### ISSUE THREAD

**Issue by ypcool** [fusetools/react-native-unity2#23]
I have encountered a problem and I don't know how to solve it. I am not an Android developer

Your hardware does not support this application

Failed to load 'libmain.so'

java.lang.UnsatisfiedLinkError: dlopen failed: library 'libmain.so' not found

Press OK to quit.

**Comment by mortend** [comment]
Did this happen on Android Emulator?

I have experienced this on Android Emulator but didn't fix the problem since it works well on real devices.

It seems something goes wrong with the libmain.so library when running on Android Emulator.

**Comment by ypcool** [comment]
Yes, there was an error on the Android emulator. I tried to package and run it on the real machine, but there was an error in packaging
I don't know what to do, I don't know if it's a problem with ARM

**Comment by mortend** [comment]
What was the error?

**Comment by ypcool** [comment]
Now it can run on the real machine
tks
But the simulator still doesn't work
