### ISSUE TITLE
Android app crashed when going from React Native to Unity second time

### ISSUE THREAD

**Issue by thanhvd** [fusetools/react-native-unity2#24]
There are 2 parts in my app, the first one is built with React Native (for forms, settings, reports,...) and the second one is built with Unity (for games). Users can switch between the 2 parts when using the app. It works fine on iOS but not on Android.

The Android app crashed when going from React Native to Unity the second time, the first time has no problem.

Steps to reproduce:
1. RN to Unity -> ok
2. Unity to RN -> ok
3. RN to Unity again -> crashed

![Screenshot 2023-06-21 at 21 49 00](https://github.com/fusetools/react-native-unity2/assets/6635396/07f143d5-eddc-4315-aec7-eff7832e9836)

![Screenshot 2023-06-21 at 21 43 50](https://github.com/fusetools/react-native-unity2/assets/6635396/aea1d742-6751-44b8-99fb-0fc70e84f9ba)

Please help me to find the root cause to fix it.

Thanks.

**Comment by mortend** [comment]
Hi,

The crash can be fixed by turning off Multithreaded Rendering in Unity project settings:

![image](https://github.com/fusetools/react-native-unity2/assets/247798/59e3c86f-fd55-4293-b3a7-723a7264c43c)

**Comment by thanhvd** [comment]
I found out that it crashed because of events  "onDropViewInstance" and "Restarting Unity player" repeated many times. On a react native screen, Unity could be rendered when the state "loading" changes to "false", if the state changes many times, it makes those events called many times too. I solved it by removing the condition "loading".

I will try your suggestion, thanks @mortend.
