### ISSUE TITLE
npm unable to download typescript-4.6.4.tgz from nexus.fuse.ninja when running npm install?

### ISSUE THREAD

**Issue by ROBYER1** [fusetools/react-native-unity2#3]
npm seems unable to download from this link during the npm install command `npm install react-native-unity2`

https://nexus.fuse.ninja/repository/npm-registry/typescript/-/typescript-4.6.4.tgz

I tried the link in my browser and it won't load there either, I'm just using a home network - no fancy proxy or VPN or anything of the like and I do all development on this home network.

Is there a ways to have these files stored somewhere other than a private website in case the worst should happen and the site went down as people wouldn't be able to use this react native implementation either.

Error:
```
npm ERR! code ETIMEDOUT
npm ERR! syscall connect
npm ERR! errno ETIMEDOUT
npm ERR! network request to https://nexus.fuse.ninja/repository/npm-registry/typescript/-/typescript-4.6.4.tgz failed, reason: connect ETIMEDOUT 192.168.20.83:443
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'
```

**Comment by mortend** [comment]
This should be fixed by #4 (merged).
