### ISSUE TITLE
how much does it add to the final apk size, and loading time?

### ISSUE THREAD

**Issue by pierroo** [fusetools/react-native-unity2#34]
Hi,

I am eager to try this, however I had a question: on a template default react native app, the size is around 20Mb or less.

1- how much does the unity template add to the final built apk size?
2- does it affect the loading time of the app? even if the unity is in a different screen than the home page for example?
a default rn app would load within a second, can we expect the same when integrating unity?

**Comment by mortend** [comment]
Hi,

1. At least a few megabytes I'd say, depending on how much content is included in your Unity project. The example app in this repo is 97M when built which seems a bit large when compared to your 20Mb. I am not sure how to measure it correctly.

```
➜  example git:(main) du -h android/app/build/outputs/apk/debug/app-debug.apk 
 97M	android/app/build/outputs/apk/debug/app-debug.apk
```

2. The loading time of the app isn't affected noticeably by including Unity. The page you put your Unity content on will have its own loading screen inside the Unity view.

**Comment by pierroo** [comment]
thank you for your answer, that's reassuring for the loading time; as for the apk size I will try it myself to confirm :)
