### ISSUE TITLE
Frozen Unity player (sound plays) on 2nd navigation to UnityView screen.

### ISSUE THREAD

**Issue by entelostre** [fusetools/react-native-unity2#35]
Hello, I have a strange behaviour showing a frozen unity player (sound plays) when I navigate to UnityView screen for the second time.

**Comment by mortend** [comment]
Hello,

I have seen a similar problem. I think the solution was to turn off `Multithreaded Rendering` in Unity Player Settings for Android when exporting the project from Unity.
