### ISSUE TITLE
'UnityFramework/UnityFramework.h' file not found.

### ISSUE THREAD

**Issue by Bruce-zxy** [fusetools/react-native-unity2#6]
After I installed `react-native-unity2` with `yarn`, I executed `pod install`, but I have not yet imported the Unity-Phone project in Xcode. After running `react-native run ios`, this error will be thrown in the terminal. 

I'm not sure if the problem is caused by the fact that I'm using a virtual machine.

![image](https://user-images.githubusercontent.com/22904758/195549053-a89d6d03-1881-4c86-aa64-8cba430ecb8f.png)

**Comment by Bruce-zxy** [comment]
After importing the Unity-iPhone project in Xcode, and refer to the UnityFramework, it works.

**Comment by yudizhemal** [comment]
@Bruce-zxy can you please guide me how can i import Unity-iPhone project in Xcode do we have to import in our react native project or what are the steps

Thanks
